# Generated by Django 2.0 on 2018-04-17 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
