# Generated by Django 2.0 on 2018-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_signup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='date',
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
